// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPPzKwSJSz3BFciHAMRQJskiQSu0dQSsY',
    appId: '1:683737789737:web:11af69152d3ab61ea63338',
    messagingSenderId: '683737789737',
    projectId: 'todo-app-4fca5',
    authDomain: 'todo-app-4fca5.firebaseapp.com',
    storageBucket: 'todo-app-4fca5.appspot.com',
    measurementId: 'G-HEZ3R0963X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmj_1rNmwF01O4S_GJ5XZ4464jZRzIw2Q',
    appId: '1:683737789737:android:118a6f5d23c32d66a63338',
    messagingSenderId: '683737789737',
    projectId: 'todo-app-4fca5',
    storageBucket: 'todo-app-4fca5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ug76FCHYwqMqESvvtphWtxmbKbeVARY',
    appId: '1:683737789737:ios:a36722c993bd5dbda63338',
    messagingSenderId: '683737789737',
    projectId: 'todo-app-4fca5',
    storageBucket: 'todo-app-4fca5.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6ug76FCHYwqMqESvvtphWtxmbKbeVARY',
    appId: '1:683737789737:ios:6950e0c21dabac66a63338',
    messagingSenderId: '683737789737',
    projectId: 'todo-app-4fca5',
    storageBucket: 'todo-app-4fca5.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
